DOWNLOAD_DELAY = 1 
USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'
HTTPCACHE_ENABLED = True
HTTPCACHE_EXPIRATION_SECS = 0
HTTPCACHE_DIR = 'httpcache'
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 1
AUTOTHROTTLE_MAX_DELAY = 10
AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0
FEED_EXPORT_ENCODING = 'utf-8'
CONCURRENT_REQUESTS = 8  
DOWNLOAD_DELAY = 0.5    



CONCURRENT_REQUESTS_PER_DOMAIN = 2

SPIDER_MODULES = ['amazon_sa.spiders']
NEWSPIDER_MODULE = 'amazon_sa.spiders'
