name: Scrape and Generate Notebooks

on:
  workflow_dispatch:

jobs:
  scrape-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install scrapy beautifulsoup4 lxml requests nbformat

      - name: Run Noon Scraper
        run: scrapy runspider noon_sa/noon_sa/spiders/noon_sa.py

      - name: Debug list json
        run: ls -lh *.json

      - name: Generate notebooks
        run: python generate_notebooks.py

      - name: Upload notebooks
        uses: actions/upload-artifact@v4
        with:
          name: rendered-notebooks
          path: |
            notebook_noon.ipynb
            notebook_amazon.ipynb
