name: Run Noon Scraper Daily

on:
  schedule:
    - cron: '30 15 * * *'  # 6:30 PM EEST (2:30 PM UTC)
  workflow_dispatch:       # Manual trigger from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install scrapy beautifulsoup4 lxml requests

      - name: Run Noon Scraper
        run: scrapy runspider amazon_sa.py

      - name: Upload JSON Output
        uses: actions/upload-artifact@v4
        with:
          name: noon-scraped-output
          path: '*.json'
